# .github/workflows/ci.yml

name: Python CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Step 2: Set up a specific version of Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
      
      # Step 4: Install dependencies using Poetry
      # Caching is used to speed up subsequent runs
      - name: Install dependencies
        run: poetry install --only main,dev
      
      # Step 5: Run tests with pytest
      - name: Run tests
        run: poetry run pytest